networks:
  comfy_network:
    driver: bridge

services:
  comfyui-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Assuming your app runs on port 3000 inside the container
    networks:
      - comfy_network
    restart: unless-stopped
    environment:
      - PORT=3000
      - COMFYUI_HOST=192.168.1.19:8188
      - COMFYUI_USE_SSL=false
      # Add any other necessary environment variables
    volumes: # Optional: for local development to see code changes without rebuilding image
      - ./server.js:/usr/src/app/server.js
      - ./app.js:/usr/src/app/app.js
      - ./workflows.js:/usr/src/app/workflows.js
      - ./imageUtils.js:/usr/src/app/imageUtils.js
      - ./comfyuiService.js:/usr/src/app/comfyuiService.js
      - ./routes:/usr/src/app/routes

# You can optionally define your ComfyUI service here too if you run it via Docker
# services:
#   comfyui:
#     image: <your_comfyui_docker_image> # e.g., comfyui/comfyui or a custom build
#     ports:
#       - "8188:8188"
#     networks:
#       - comfy_network
#     # Add volumes for models, custom nodes, etc.
#     # Add GPU capabilities if needed: deploy: { resources: { reservations: { devices: [ { driver: 'nvidia', count: 1, capabilities: [gpu] } ] } } }